### ISSUE TITLE
[REQUEST] Cache support

### ISSUE THREAD

**Issue by adammakowskidev** [luizfonseca/proksi#48]
**Is your feature request related to a problem? Please describe.**
First, basic cache support.

**Describe the solution you'd like**
It would be nice if Proksi used tinyufo for better performance.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by luizfonseca** [comment]
Currently in progress 👍🏽 

These are the ones I'm building:

- DiskCache + Memory lookup
- MemoryCache
- TinyUfoCache

**Comment by luizfonseca** [comment]
Cache support has been mostly added in https://github.com/luizfonseca/proksi/releases/tag/v0.3.20

`tinyufo` will be added in a later release, but the current code is able to:

- cache files to disk
- keep recent files in memory
- change configuration about stale times/cache lock

What is coming after:
- Purging/Eviction
- TinyUfo support as the memory layer for any caching
